### ISSUE TITLE
Open/close tab sequence issue

### ISSUE THREAD

**Issue by bodisor** [harytfw/GlitterDrag#105]
The default behavior (of this extension) for tab switching after closing **current child** tab is to always open parent tab.., regardless of settings. Even selecting '_after closing all children tabs, switch to parent_' does not override this behavior.

I think the problem lies in the tab opening sequence, because the '_don't adjust tabs opening sequence_' does the opposite of what it should (in terms of children tabs). In other words, it opens  each child tab immediately next to parent.
Example:
when '_don't adjust tabs opening sequence_' is checked, instead of firefox default behavior
(parent > child1 > child 2 > child 3)
this extensions moves previously opened child to make room (next to parent) for the last opened child, resulting in:
(parent > child 3 > child 2 > child 1)

De-selecting '_don't adjust tabs opening sequence_' switches to firefox default behavior (which is counter intuitive). But the switch to parent tab (when closing any child) happens regardless of any of those two settings.

Firefox default behavior is this:
parent > child1 > child2 > child3
- if closing child1, firefox switches to child2
- if closing child2, firefox switches to child3
- if closing child3, firefox goes to parent **only** if there are no other parents after child3

This extension (regardless of settings) always switches to parent when **any** child is closed.

I hope I explained it properly. Firefox default behavior would be appreciated.

I've tested this on a clean profile, without any other extensions and without any modifications to prefs.js (or user.js).

**Comment by harytfw** [comment]
Some explanation:
The tab sequence case : (parent > child 3 > child 2 > child 1) 
is the deafult behavior of the extension.

In order to respect firefox behavior (see #16 ) I added this feature and make it enable.
But I also hope users can control the sequence of tabs, the option become "don't adjust tabs opening sequence". The name of option may be ambiguous.


After fixing #86, The two options "After closing current tab, ... " and option "After closing all children tabs，... " can't do the expected work.
So in the next version, I will delete these two option and also hide option "don't adjust tabs opening sequence".

The problem also relates to config "browser.tabs.selectOwnerOnClose"(default is true)
because fixing #86 makes every child tab opened by extension has record of their parent tab. After you close one child tab, the parent tab will be selected.Closing the other children tabs will do the same.

However, If you manually open more than one child tab(don't use this extension), these children tabs will lose the record and do what you mention.
>   if closing child1, firefox switches to child2
>   if closing child2, firefox switches to child3
>   if closing child3, firefox goes to parent only if there are no other parents after child3

**Comment by bodisor** [comment]
I see...

At the moment I'm using 'Select After Closing Current' extension along 'Glitter Drag', in order to "revert" to firefox default behavior. I guess I could disable '_browser.tabs.selectOwnerOnClose_' instead of using another extension, but this setting is still useful.

Thanks for clarification.
