### ISSUE TITLE
critical feature issue.

### ISSUE THREAD

**Issue by drmusti** [harytfw/GlitterDrag#50]
add feature min max px
example only action  min 15px  - max 165 px etc.   
because i drag to link jdownloader and unfortunately action ...

please   add custom min-max values.

and ff 57 sometimes dont work. i must refresh page and try again. later again work. 
this bug very offen. borred. very bad proplem.

Sincerely.

**Comment by Qwash** [comment]
Hello @drmusti 
You can enable "Permit different actions when press Ctrl Key"
a new tab will apear "Actions with Ctrl Key"
in the new tab configure all directions to "Only 1 directions" and "No action"


Instead of limiting the activation with min px not triggering GD if Ctrl is down is a much better option.

**Comment by drmusti** [comment]
okay but sometimes dont work extention ff57 . why?

**Comment by harytfw** [comment]
Thanks @Qwash
Adding minimum and maximum distance is a good idea, I will implement this feature.

Because I can't reproduce your problem, I recommend you check whether it is a extension confliction by disabling all extensions except this extension.Or just create a new profile and install Glitter Drag.

**Comment by drmusti** [comment]
okay but sometimes dont work extention ff57 . why?  proplem is ff or extention?

**Comment by harytfw** [comment]
Hi @drmusti , I upload a latest version, and it may fix the problem you encouter.
Please let me know if it can work well.

https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/versions/

**Comment by drmusti** [comment]
***and at v1.53 fixed "sometimes dont working bug" :)) thanks for fix.
***min-max values great working thanks this feature .
***at 1.53 custom css proplem fixed.
*** good works 
---bug 01 : but if at new window result option right dont work.
if at new window try drag ( option selected right... ) result always last adding..please fix this bug...... at main window no proplem.
---bug02: at iframe , frame  dont show promptbox...  for test link: http://urlmidi.com/test    #GDPrompt no showing.

***new issue: VK videos drag drop to notepad++ or to jdownloader please dont action. any different software vk videolinks please no action.
Sincerely Big Coder.
