### ISSUE TITLE
new critical bug

### ISSUE THREAD

**Issue by drmusti** [harytfw/GlitterDrag#68]
[http://prntscr.com/hsylf3](url)

http://prntscr.com/hsylf3

:((  critical bug

**Comment by harytfw** [comment]
Sorry for my mistake. I make a detection to see if the extension is loaded sucessfully (due to [#65](https://github.com/harytfw/GlitterDrag/issues/65)). It seems that the extension always work.
It turns out that the detection is fail or don't work as expected.
You should re-install 1.53.1 if the notification is annoying
