### ISSUE TITLE
How to get rid of hardcoded Chinese text? and other issues with the panel

### ISSUE THREAD

**Issue by mario98** [harytfw/GlitterDrag#97]
In the panel, there is some hardcoded Chinese text. How can I get rid of this / replace it with English Text? (see below)

Also if you select "no action" for certain elements in the panel, the buttons are still shown but shrunk to a minimal size. It would be more elegant to just hide the buttons then.

Also the panel flickers sometimes (especially if you have chosen no action for some buttons) because the panel expands if you hover over an element whose text is too large but then as it expands the button moves away from the mouse cursor so the text changes back to the original and the panel shrinks again, so that the button moves back under the mouse cursor and then the panel expands because the text of this button is too large and so on... It would be more elegant to make the panel fixed size, just make sure that no text is too large (you can truncate too long text with ...)

Also I find it more useful if the panel would appear with the upper left corner under the mouse cursor instead of having the middle of the panel under the mouse cursor. (Or even better you could make it dependent on the drag direction, i.e. place the panel such that it appears in that direction you dragged the content. e.g. you drag to the left, make the panel appear left to the cursor, you drag to the right, make the panel appear right to the cursor. Because once the panel appears, the mouse still has some momentum left and then "overshoots")

I hope you can improve the panel a little based on my feedback, because it has great potential and I really love the idea of having a panel. I already used Super Drag which has similar functionality but was destroyed by Mozilla pyromaniacs who set 80% of the addons on fire.

P.S. Here is a screenshot of the hardcoded Chinese text:
![Image](http://fs5.directupload.net/images/180606/issw2m9d.png)

**Comment by harytfw** [comment]
Thanks for your long and helpful feedback.
The panel is still in development and it needs more test.(Perhaps I should hide it on options page)
Recent weeks I spend more time on the development of panel to fix or improve it.

Super Drag is a good addon though I didn't use it before(I used Easy DragToGo+).
#47 requests making a function like Super Drag, then I found it is very useful that you can select those actions which are not often used.

About the hardcode Chinese text, it was localized, so you won't see it because of your localization.

About the 2nd problem(flickers),I think it was solved.

About the 3rd problem, I make a adjustment following your advice that place the panel such that it appears in that direction you dragged the content.

About the 1st problem, I can't fully understand what you mean or maybe I can't reproduce it.

![gif](https://user-images.githubusercontent.com/14118053/41158307-0890de3c-6b5b-11e8-8cef-23aa6b0bb14c.gif)

**Comment by mario98** [comment]
Thanks for the detailed answer.

Regarding the first issue, maybe it is because I have a non-english (German) locale? Maybe if the translation for a specific language can not be found, it will fall back to the default (which is Chinese)?

I know this makes things complicated, but I'd rather have English text than Chinese text. Can this be implemented?

**Comment by harytfw** [comment]
It is my fault that leaving these hardcode chinese text in source code.
It's not your business

v1.55 fixes this bug and you can install the latest version at https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/

**Comment by mario98** [comment]
Thank you so much. But in the most recent version I noticed there is a circle representing the drag distance, even though I have not changes any options (i.e. "distance tip" or whatever this is is disabled)

**Comment by harytfw** [comment]
now it is fixed
